import type { Metadata } from "next";
import { Sora, Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import SlipPanel from "@/components/layout/SlipPanel";

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${sora.variable} ${inter.variable} ${jetbrainsMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground overflow-hidden">
        <Header />
        
        {/* Main Application Area */}
        <div className="flex-1 flex max-w-[1440px] mx-auto w-full h-[calc(100vh-64px)]">
          {/* Slip Panel Column (Your Slip) - Moved to Left */}
          <aside className="hidden md:flex w-[35%] lg:w-[30%] shrink-0 h-full p-6 pr-0">
            <SlipPanel />
          </aside>

          {/* Main Workspace Column (Discover/Selection Container) */}
          <main className="flex-1 flex flex-col w-full h-full overflow-y-auto px-4 md:px-6 py-6 lg:w-[70%] md:w-[65%]">
            {children}
          </main>
        </div>

        {/* Mobile Floating Action Bar (Visible only on mobile when slip has items) */}
        <div className="md:hidden fixed bottom-4 left-4 right-4 z-50">
           <div className="bg-primary text-primary-foreground shadow-lg rounded-lg px-6 py-3 flex items-center justify-between font-medium">
              <span>3 Legs Added</span>
              <div className="flex items-center gap-2">
                 <span className="text-primary-foreground/80">•</span>
                 <span>View Slip</span>
              </div>
           </div>
        </div>
      </body>
    </html>
  );
}
